
#
# Ok - CloudFlare
# baseURL = "https://sergiolllopez.pages.dev/" => HUGO_BASEURL
# GitLab
# https://gitlab.com/<YourUsername>/<your-hugo-site>/pipelines
# https://<YourUsername>.gitlab.io/<your-hugo-site>/
# Ok - GitHub
# User/Organization Pages (https://<USERNAME|ORGANIZATION>.github.io/)
# Project Pages (https://<USERNAME|ORGANIZATION>.github.io/<PROJECT>/) => HUGO_BASEURL
# Ok - Netlify
# baseURL = "https://sergiolllopez.netlify.app/" => HUGO_BASEURL
#

languageCode = "en-us"
title = "sergiolllopez"

theme        = "hello-friend-ng"
paginate     = 10

publishDir   = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Mis cosas"
  keywords = "homepage"
  images = [""]

[taxonomies]
    category = "me"
    tag      = "tags"
    series   = "series"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/"

[[params.social]]
  name = "github"
  url = "https://github.com/"

[[params.social]]
  name = "gitlab"
  url = "https://gitlab.com/"

[[params.social]]
  name = "bitbucket"
  url = "https://bitbucket.com/"

[[params.social]]
  name = "slack"
  url = "https://slack.com/"

[languages]
  [languages.en]
    title = ""
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "sergiolllopez"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "me"
    name       = "Me"
    url        = "/me"

